[package]
name = "rs_bak_prod"
version = "0.1.0"
edition = "2021"

# See more keysx and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4"
lettre = "0.11"
chrono-tz = "0.8.5"
#lettre_email = "0.9"
#sendmail = "=2.0.0"
